name: 'discord-notify'

# status, discord_webhook_url 값을 받아서 사용
inputs:
  status:
    required: false
    default: 'failure'
  discord_webhook_url:
    required: true

  # using: 'composite' 통해 직접 Action 생성을 명시
  runs:
    using: 'composite'

    steps:
      - name: Send Discord
        shell: bash
        run: |
          if [ "${{ inputs.status }}" = "success" ]; then
            EMOTICON="✅"
          else
            EMOTICON="⛔"
          fi

          MSG="{"content": ${EMOTICON}, "username": "LoggerBot", "avatarUrl": "https://phinf.pstatic.net/contact/20240821_205/1724202038449ujiun_JPEG/image.jpg","tts": false }"

          curl -X POST -H 'Content-type: application/json' --data "${MSG}" "${{ inputs.discord.webhook_url }}"
